"""empty message

Revision ID: 439691a7ab11
Revises: 
Create Date: 2024-07-12 19:50:20.742355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439691a7ab11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('idx', sa.Integer(), nullable=False, comment='primary key'),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_tbl_user_created_at'), 'tbl_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_user_name'), 'tbl_user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_user_name'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_created_at'), table_name='tbl_user')
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
